# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pySteganoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 314)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(0, 170, 90, 28))
        self.btnClear.setObjectName("btnClear")
        self.labelPic = QtWidgets.QLabel(self.centralwidget)
        self.labelPic.setGeometry(QtCore.QRect(240, 20, 256, 256))
        self.labelPic.setText("")
        self.labelPic.setScaledContents(True)
        self.labelPic.setObjectName("labelPic")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(320, 280, 90, 28))
        self.btnLoad.setObjectName("btnLoad")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(230, 280, 90, 28))
        self.btnSave.setObjectName("btnSave")
        self.btnHide = QtWidgets.QPushButton(self.centralwidget)
        self.btnHide.setGeometry(QtCore.QRect(90, 170, 111, 28))
        self.btnHide.setObjectName("btnHide")
        self.btnUnhide = QtWidgets.QPushButton(self.centralwidget)
        self.btnUnhide.setGeometry(QtCore.QRect(410, 280, 90, 28))
        self.btnUnhide.setObjectName("btnUnhide")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 201, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 0, 251, 19))
        self.label_3.setObjectName("label_3")
        self.editA = QtWidgets.QLineEdit(self.centralwidget)
        self.editA.setGeometry(QtCore.QRect(110, 200, 91, 29))
        self.editA.setObjectName("editA")
        self.editB = QtWidgets.QLineEdit(self.centralwidget)
        self.editB.setGeometry(QtCore.QRect(110, 230, 91, 29))
        self.editB.setObjectName("editB")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 81, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 81, 19))
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 20, 201, 141))
        self.textEdit.setObjectName("textEdit")
        self.editSeed = QtWidgets.QLineEdit(self.centralwidget)
        self.editSeed.setGeometry(QtCore.QRect(110, 260, 91, 29))
        self.editSeed.setObjectName("editSeed")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 81, 19))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Прячем текст в картинке"))
        self.btnClear.setText(_translate("MainWindow", "Стереть"))
        self.btnLoad.setText(_translate("MainWindow", "Загрузить"))
        self.btnSave.setText(_translate("MainWindow", "Сохранить"))
        self.btnHide.setText(_translate("MainWindow", "Спрятать"))
        self.btnUnhide.setText(_translate("MainWindow", "Извлечь"))
        self.label_2.setText(_translate("MainWindow", "Текстовая информация"))
        self.label_3.setText(_translate("MainWindow", "Картинка"))
        self.editA.setText(_translate("MainWindow", "13"))
        self.editB.setText(_translate("MainWindow", "17"))
        self.label_4.setText(_translate("MainWindow", "Ключ A"))
        self.label_5.setText(_translate("MainWindow", "Ключ B"))
        self.editSeed.setText(_translate("MainWindow", "256"))
        self.label_6.setText(_translate("MainWindow", "Ключ SEED"))
